# Site
repository: sproogen/resume-theme
# favicon: images/favicon.ico

# Personal info
name: Michael Pavlukhin
title: Data Scientist & Backend Developer
email: alivemihail@gmail.com
website: archelunch.github.com

# Social links
twitter_username: mike_pavlukhin
github_username:  Archelunch
# dribbble_username: jekyll
facebook_username: michael.pavlukhin
# flickr_username: jekyll
instagram_username: michael.pavlukhin
linkedin_username: mpavlukhin
# pinterest_username: jekyll
#youtube_username: globalmtb
# googleplus_username: +jekyll

# About Section
# about_title: About Me
about_profile_image: images/46804317_2209367055977613_3594375761139597312_o.jpg
about_content: | # this will include new lines to allow paragraphs
  Hi, my name's Michael. I am Data Scientist and Backend Developer. I like reading Medium and new papers on Arxiv and always try to test it myself. Also I'm practicing <mark>design thinking</mark>.


# Projects Section
# projects_title: Projects

# Experience Section
# experience_title: Experience

# Education Section
# educaton_title: Education

# More Section
# more_title: A Little More About Me
more_content: | # this will include new lines to allow paragraphs
  My skills:
   - Python
   - Pytorch
   - Django
   - Flask
   - Redis
   - SQL
   - Golang
   - ML&DL
   - Design Thinking
   - Singing

# Footer
footer_show_references: true

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
